configs/letsencrypt/init-letsencrypt.sh
templates/aws/eb/Preview/.ebextensions/ssl.config.dist
templates/aws/eb/Single/.ebextensions/ssl.config.dist
templates/aws/eb/Single/README.md
templates/linux/setup.sh

* `docker-compose exec -T ` to allow use without a tty
* `--non-interactive` to remove certbot warning: `Skipped user interaction because Certbot doesn't appear to be running in a terminal. You should probably include --non-interactive or --force-interactive on the command line.`
* `--data_path` option to override default path

fix: add data path customization

---

configs/letsencrypt/init-letsencrypt.sh
templates/aws/eb/Preview/.ebextensions/ssl.config.dist
templates/aws/eb/Preview/.platform/hooks/postdeploy/01_setup_ssl.sh.dist
templates/aws/eb/Single/.ebextensions/ssl.config.dist
templates/aws/eb/Single/.ebignore
templates/aws/eb/Single/.gitignore
templates/aws/eb/Single/.platform/hooks/postdeploy/01_setup_ssl.sh.dist
templates/aws/eb/Single/README.md

* Moves running lets-encrypt ssl certificates generation from `container_commands` which runs after setting up the file, but before deployment to `postdeploy hooks` which happens after the deployment.

Fix ssl interferance lifecycle

---

.github/workflows/linux-install.yml
templates/linux/Makefile
templates/linux/setup.sh

Canonical, the company behind Ubuntu, announced that the Ubuntu 16.04 LTS (Long Term Support) period will end on Friday, April 30, 2021 [1].

Drop support for Ubuntu 16

---

templates/linux/setup.sh

Adds a URL containing the public server IP address to the successful message at the end of the script for convenience. 
```
You can now open your web browser to the following address and run
the SupportPal installer.
http://127.0.0.1/
```
It does assume the server is public, the URL shown will not work for private servers. I am assuming that server admins with private servers will know the URL they would need to visit.

feat(linux): add IP address URL to success message

---

templates/linux/setup.sh

fix(linux): php-fpm address already in use on rhel 8.3

---

templates/linux/setup.sh

Fixes web installer error on RHEL / Centos using form default database hostname (`127.0.0.1`):
```
There was an error. You may need to empty the database before starting again.
SQLSTATE[HY000] [2002] Permission denied
```

fix(linux): enable selinux httpd_can_network_connect

---

templates/docker-compose/.env.dist

Rather than asking them to insert `DOMAIN_NAME` to .env, we can have it there so it's easier to set.

chore: add DOMAIN_NAME parameter to .env.dist

---

templates/docker-compose/Makefile

`make install` now uses the web installer.
You have the option of using an undocumented `make install_cli` to use the old method (slightly less user friendly, but significantly faster).

feat(docker-compose): default to web installer

---

templates/docker-compose/.env.dist
templates/docker-compose/Makefile.dist
templates/docker-compose/docker-compose.secrets.yml.dist

`$PWD` was used to allow usage in dev environments where we're mixing multiple `docker-compose.yml` files which exist in different directories. 
`$PWD` variable is not available on all shells/environments. 
Relative path support is missing from `docker` cli (`https://github.com/docker/cli/issues/1203`). So, this PR replaces docker cli `$PWD` usages with `docker-compose` which has relative path support (`.` notation).
> You can mount a relative path on the host, which expands relative to the directory of the Compose configuration file being used. Relative paths should always begin with `.` or `..`.
https://docs.docker.com/compose/compose-file/compose-file-v3/

chore: remove pwd and replace with docker-compose .

---

.github/workflows/ci.yml
templates/docker-compose/setup.sh

The purpose of this script is to check the correct versions of prerequisites currently listed on https://docs.supportpal.com/current/Deploy+on+Docker are installed. It gives some helpful tips when things are missing or the appropriate version is installed.
It also has interactive and non-interactive mode which handles the [ConfigureDockerCompose](https://docs.supportpal.com/current/Deploy+on+Docker#ConfigureDockerCompose) steps.
Missing docker:
```
$ bash setup.sh 
checking for docker ... found /usr/bin/docker
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied
You may need to add your user to the docker group and then …
```

Add bash script to install via docker-compose

---

templates/docker-compose/Makefile.dist

This PR switches the `docker-compose` template to use the SupportPal CLI installer. helpdesk#2620 was added in v3.5.0 and allows us to feed in the database details rather than the user having to provide them.
> helpdesk#2620 | Added app:install options to pass database details non-interactively.
https://docs.supportpal.com/current/3.5.0 
----
The `mysqladmin ping` was necessary as `app:install` immediately validates the provided database details. It returns `Connection refused` if you don't wait for MySQL to be fully up.

Provide DB details to docker installer

---

templates/docker-compose/Makefile.dist

```
docker exec db bash -c "while ! (mysqladmin ping -uroot -p$(cat secrets/db_root_password.txt) --silent); do sleep 1; done"
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface …
```

Fix connection refused in docker-compose install

---

templates/linux/setup.sh

Linux command currently produces:
````
Archive:  /tmp/supportpal.zip
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/supportpal.zip or
/tmp/supportpal.zip.zip, and cannot find /tmp/supportpal.zip.ZIP, period.
````
This is due to public access to `supportpal.com/manage/downloads/` being recently blocked.
Download URLs are now accessible from the license server.

fix(linux): unable to download latest SupportPal version

---

configs/gateway/base.conf
configs/gateway/custom.conf
configs/gateway/nginx-http.conf
configs/gateway/nginx-https.conf
templates/aws/eb/HA/cron/docker-compose.yml.dist
templates/aws/eb/HA/web/docker-compose.yml.dist
templates/aws/eb/Preview/docker-compose.yml.dist
templates/aws/eb/Single/docker-compose.yml.dist
templates/docker-compose/docker-compose.yml.dist

This PR is a fresh attempt at https://github.com/supportpal/helpdesk-install/pull/47 which was subsequently reverted in https://github.com/supportpal/helpdesk-install/pull/49
The main benefit of this PR is that the duplication between `nginx-http.conf` and `nginx-https.conf` has been removed.
Users can modify all config files but are encouraged to make any additions in `custom.conf`

refactor(docker): nginx config

---

templates/linux/setup.sh

Two issues:
* When the root password begins with special characters the command is unable to connect:
```console
mysql -uroot '-p(25@Qzxn7\,vN];' -e 'CREATE DATABASE supportpal;'
Warning: arning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES
```
* The `GRANT` statement is the wrong way around. This only works at the moment because `$username` and `$database` are the same value (`supportpal`).

fix(linux): mysql statements

---

templates/linux/setup.sh

Fixes on CentOS:
```
main: line 472: pwgen: command not found
```

fix(linux): pwgen not found on centos

---

.github/workflows/linux-verify.yml
templates/linux/setup.sh

`yum` is troublesome and requires dropping the error catching mode temporarily. EL8 should be used instead to reduce the main of different logic we need to maintain.

feat(linux): drop el7 support

---

templates/linux/setup.sh

Enable HTTPS in the firewall on CentOS 8. Saves the user the bother even though it's not setup yet. Apache isn't listening on port 443 by default so the port is closed.

feat(linux): permit https in firewall-cmd

---

templates/docker-compose/Makefile.dist

https://docs.supportpal.com/current/Deploy+On+Docker#StartContainers is currently a step which one must run manually.
We can do it for the user after the `app:install` command has completed.
docs.supportpal.com will be updated to reflect this PR.

feat(docker): run make restart after installation

---

templates/linux/setup.sh

The goal of this PR is to solve the following issues:
- Replace the ioncube download URL from HTTP to HTTPS
- Add the missing optional PHP ZIP extension to the installation

fix: update ioncube url and add missing ext

---

templates/docker-compose/setup.sh

All of the docker-compose yml files use docker-compose 3.8 syntax. 3.8 syntax was only added in 1.25.5 (https://docs.docker.com/compose/release-notes/)
Using docker-compose 1.25.0 you get:
```console
$ docker-compose -f docker-compose.secrets.yml run --rm -T configurator
ERROR: Version in "./docker-compose.secrets.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

fix(docker-compose): require docker-compose >=1.25.5

---

.github/workflows/linux-verify.yml

CentOS moved their docker images to quay.io and CentOS 8 is now EOL with the repositories being moved to vault.centos.org - https://stackoverflow.com/a/70930049/2653593

ci(linux): test on centos 8 stream

---

configs/letsencrypt/create-self-signed.sh
configs/letsencrypt/init-letsencrypt.sh
templates/docker-compose/docker-compose.https.yml

Fixes issue: #89 
The issue is fixed by explicitly referring to the new files instead of relying implicitly on docker-override.yml

fix: adapt https to 4.0 structure

---

configs/gateway/base.conf

Create a `.html` file in `/resources/assets` and try to load it. It will show the SupportPal 404 error page.
Suspect this will probably break usage on sub directory installations like `https://company.com/support/resources/assets/...` - needs further testing. Maybe need to use regex - http://nginx.org/en/docs/http/ngx_http_core_module.html#location

fix: allow access to any file in /resources/assets

---

templates/docker-monolithic/upgrade.sh

It's possible that the server is running an older version of docker and doesn't have `docker compose` (v2) installed. We should check, and get them to install it if it's not available.

chore: check for docker compose in upgrade.sh

---

templates/aws/eb/HA/cron/docker-compose.yml.dist
templates/aws/eb/HA/web/docker-compose.yml.dist
templates/aws/eb/Preview/docker-compose.yml.dist
templates/aws/eb/Single/docker-compose.yml.dist
templates/docker-compose/docker-compose.prod.yml
templates/docker-compose/docker-compose.yml

In v4.0 we're removing the OS from the image names as we don't intend to maintain multiple images with different OS versions i.e. buster and bullseye. Buster is also EOL soon and we don't want to have to change the image name every X years based on Debian's EOL policies.

chore(docker): remove os from image names

---

templates/docker-monolithic/setup.sh

```
In setup.sh line 20:
shift
^---^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
```
I prefer to keep the line because if we add more options in the future then we'll no doubt forget to add `shift` back.

fix: shellcheck notice

---

templates/docker-monolithic/docker-compose.yml

We want to send requests to caddy rather than Apache. caddy will handle HTTP to HTTPS redirects if appropriate.
`upgrade.sh` overwrites `docker-compose.yml` and https://docs.supportpal.com/current/Upgrade+Guide#UpgradeDockerMonolithic recommends to run it, so I think this change should be OK.

fix: send requests to caddy rather than apache

---

templates/docker-monolithic/backup.sh

https://docs.docker.com/engine/reference/commandline/cp/
> `DEST_PATH` does not exist and ends with `/`
>    Error condition: the destination directory must exist.

fix(docker-monolithic): no such directory on backup

---

templates/docker-monolithic/restore.sh

Fixes the below:
```
Stopping services...
sshd
warning: /etc/service/sshd: unable to open supervise/ok: access denied
cron
warning: /etc/service/cron: unable to open supervise/ok: access denied
horizon
warning: /etc/service/horizon: unable to open supervise/ok: access denied
caddy
warning: /etc/service/caddy: unable to open supervise/ok: access denied
meilisearch
warning: /etc/service/meilisearch: unable to open supervise/ok: access denied
apache
warning: /etc/service/apache: unable to open supervise/ok: access denied
ws
warning: /etc/service/ws: unable to open supervise/ok: access denied
phpfpm
warning: /etc/service/phpfpm: unable to open supervise/ok: access denied
postfix
warning: /etc/service/postfix: unable to open supervise/ok: access denied
```

fix(docker-monolithic): stopping services in restore.sh

---

templates/docker-monolithic/backup.sh
templates/docker-monolithic/restore.sh

Piping to `/dev/null` makes it impossible to understand why the script is failing.

fix(docker-monolithic): remove pipes to /dev/null

---

templates/linux/setup.sh

Oracle seem to have changed the apt repository key which causing `apt-get` requests to fail on nightly builds.

fix(linux): update mysql apt repo to 0.8.29

---

templates/docker-monolithic/backup.sh
templates/docker-monolithic/restore.sh

The service names changed in 5.2.0 to `00redis` and `00mysql`

fix(docker-monolithic): backup restore scripts on 5.2.0

---

templates/docker-monolithic/backup.sh

The backup crashes after `Backing up database...` because the grep doesn't match a path.
```console
[2024-01-31 11:57:31] Backing up database...
[2024-01-31 11:57:32] Uploading backup...
[2024-01-31 11:57:33] The backup was generated at https://s3.foo.com/support.foo.com/backups/database-2024-01-31-11-57-31.sql.gz
```

fix(docker-monolithic): backup with s3 storage configured

---

templates/linux/setup.sh

Ubuntu 18 is no longer supported by ondrej's ppa.

Remove support for Ubuntu 18.04

---

templates/docker-compose/upgrade.sh

```
In upgrade.sh line 6:
${DOCKER_COMPOSE_BIN} ${COMPOSE_FILES} up -d supportpal
^--------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean:
${DOCKER_COMPOSE_BIN} "${COMPOSE_FILES}" up -d supportpal
In upgrade.sh line 7:
${DOCKER_BIN} exec -it ${WEB_SERVICE_NAME} bash /scripts/upgrade-helpdesk.sh
^-----------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean:
${DOCKER_BIN} exec -it "${WEB_SERVICE_NAME}" bash /scripts/upgrade-helpdesk.sh
For more information:
https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

fix(docker-compose): upgrade.sh shellcheck issues

---

templates/docker-monolithic/restore.sh

`app:backup` on v5.7.4 produces `app-*.tar`. https://docs.supportpal.com/current/Migrating+to+a+New+Server states to use `restore.sh` but it doesn't work because it looks for `app-*.tar.gz`. 
This MR ensures that `restore.sh` works with both `app-*.tar` and `app-*.tar.gz` files.

feat(docker-monolithic): allow restoring from .tar files
