templates/linux/setup.sh

feat(linux): check script is ran as root

---

templates/aws/eb/HA/README.md
templates/aws/eb/Preview/README.md
templates/aws/eb/Single/README.md

Steps on how to upgrade AWS EB deployments to new SupportPal versions

Add steps to upgrade SupportPal on EB deployment

---

templates/docker-compose/setup.sh

The setup script didn't allow use of MacOS, even though it's possible to install using Docker. This PR adds support for running on MacOS, and also fixes an issue with the `sed` commands where `-E` is not available on MacOS.

MacOS support

---

templates/linux/setup.sh

Ability to overwrite a prior run of the script.
Usage:
```
curl -sLS https://raw.githubusercontent.com/supportpal/helpdesk-install/master/templates/linux/setup.sh | sudo bash -s -- --overwrite
```
Closes #39

feat(linux): add overwrite option

---

templates/docker-compose/docker-compose.prod.yml.dist
templates/docker-compose/docker-compose.yml.dist

Restart policy was missing on these two containers.

feat(docker): add restart always to supportpal containers

---

configs/gateway/nginx-http.conf
configs/gateway/nginx-https.conf

feat(docker): set nginx client_max_body_size

---

configs/gateway/base.conf
configs/gateway/custom.conf
configs/gateway/nginx-http.conf
configs/gateway/nginx-https.conf

This PR adds the ability for users to customize their Nginx configuration alongside making it easier to change or add settings across HTTP/s configurations. 
To update, add, or remove any custom nginx directive, users should update the value of `custom.conf` nginx file. Referencing [nginx documentation](https://nginx.org/en/docs/).

chore: use include directives and add nginx customizability

---

templates/linux/setup.sh

fix(linux): php-fpm doesn't start on boot

---

.github/workflows/docker-monolithic-verify.yml
templates/docker-monolithic/docker-compose.yml
templates/docker-monolithic/setup.sh

Basic script which:
1. downloads and creates `docker-compose.yml` 
2. creates external docker volumes

feat: add docker monolithic setup.sh script

---

.github/workflows/linux-verify.yml
templates/linux/setup.sh

MySQL no longer support debian 9 (stretch)

chore(linux): remove debian 9 support

---

.github/workflows/docker-compose-verify.yml
.github/workflows/docker-monolithic-verify.yml
configs/letsencrypt/create-self-signed.sh
configs/letsencrypt/init-letsencrypt.sh
templates/docker-compose/Makefile.dist
templates/docker-compose/setup.sh
templates/docker-monolithic/setup.sh
templates/docker-monolithic/upgrade.sh

feat: require docker compose v2

---

.github/workflows/linux-verify.yml
templates/linux/setup.sh

Waiting on https://bugs.mysql.com/bug.php?id=107206

ci(linux): ubuntu 22.04 support

---

.github/workflows/linux-verify.yml
templates/linux/setup.sh

feat(linux): add rhel 9 support

---

templates/docker-monolithic/upgrade.sh

fix: running upgrade.sh should not duplicate domain name

---

templates/docker-compose/docker-compose.yml

https://github.com/meilisearch/meilisearch/releases/tag/v1.0.2

chore: update meilisearch to v1.0.2

---

templates/docker-monolithic/setup.sh

Copied over mailto and hostname directives from `docker-compose` setup.sh

feat(docker-monolithic): ability to set mailto directive in setup.sh

---

templates/docker-compose/MAINTENANCE.md

The suggested actions are incorrect and result in the below:
```bash
$ make upgrade
|---------------------|
|       NOTICE        |
|---------------------|
This action will upgrade your system to the latest version. We recommend that you only proceed if you've taken a recent full system backup.
You can take a backup of your system by executing: make backup
Press CTRL + C to cancel this operation. Waiting 10 seconds...
docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.https.yml -f docker-compose.custom.yml down -v
[+] Running 14/14
✔ Container supportpal_mq                 Removed                                                                          60.4s
✔ Container gateway                       Removed …
```

chore(docker-compose): update MAINTENANCE.md

---

templates/linux/setup.sh

feat(linux): add almalinux support

---

templates/docker-monolithic/setup.sh

Keep all the SupportPal docker files in one directory, rather than merging it with other stuff e.g. `/home/ubuntu/`.

feat(docker-monolithic): create installation files in unique directory

---

.github/workflows/docker-monolithic-verify.yml
templates/docker-monolithic/backup.sh
templates/docker-monolithic/restore.sh
templates/docker-monolithic/verify-restore.exp

Includes the working directory in the backup i.e. docker-compose.yml docker-compose.override.yml etc
Then when you restore, it ensures it restores to the correct version etc.

feat(docker-monolithic): include docker files in backup/restore
